package lk.ijse.Automation_Control_Service.service;

import lk.ijse.Automation_Control_Service.dto.AutomationRequestDTO;
import lk.ijse.Automation_Control_Service.entity.AutomationUnit;
import lk.ijse.Automation_Control_Service.repository.AutomationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import java.time.LocalDateTime;

@Service
public class AutomationService {

    @Autowired
    private AutomationRepository automationRepository;

    public String processAutomation(AutomationRequestDTO dto) {
        AutomationUnit action = new AutomationUnit();

        // Using the setters generated by Lombok
        action.setZoneId(dto.getZoneId());
        action.setDeviceType(dto.getDeviceType());

        // Logic: If command is "START", status is "ACTIVE". Otherwise, "INACTIVE".
        action.setActionStatus(dto.getCommand().equalsIgnoreCase("START") ? "ACTIVE" : "INACTIVE");

        action.setTriggerReason(dto.getReason());
        action.setTimestamp(LocalDateTime.now());

        automationRepository.save(action); // Persist to MySQL

        return "Successfully triggered " + dto.getDeviceType();
    }
}